# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets
2.  Load the three datasets into three tables in a SQLIte database
3.  Execute SQL queries to answer assignment questions

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Socioeconomic Indicators in Chicago</a>
2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Public Schools</a>
3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2](https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 3. Chicago Crime Data

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### Download the datasets

This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. 

Use the links below to read the data files using the Pandas library. 

* Chicago Census Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Public Schools

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Crime Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

**NOTE:** Ensure you use the datasets available on the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

### Store the datasets in database tables

To analyze the data using SQL, it first needs to be loaded into SQLite DB.
We will create three tables in as under:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

Load the `pandas` and `sqlite3` libraries and establish a connection to `FinalDB.db`

In [1]:
%pip install pandas sqlite3

Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3

In [2]:
import csv, sqlite3
import pandas as pd

con = sqlite3.connect("FinalDB.db")
cur = con.cursor()

Load the SQL magic module

In [3]:
%load_ext sql
%sql sqlite:///FinalDB.db

Connecting to 'sqlite:///FinalDB.db'

Use `Pandas` to load the data available in the links above to dataframes. Use these dataframes to load data on to the database `FinalDB.db` as required tables.

In [4]:
Census_df= pd.read_csv("ChicagoCensusData.csv")
Census_df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False, method="multi")

Public_Schools_df=pd.read_csv("ChicagoPublicSchools.csv")
Public_Schools_df.to_sql("CHICAGO_PUBLIC_SCHOOLS", con, if_exists='replace', index=False)

Crime_df=pd.read_csv("ChicagoCrimeData.csv")
Crime_df.to_sql("CHICAGO_CRIME_DATA",con, if_exists='replace', index=False, method="multi")

533

Establish a connection between SQL magic module and the database `FinalDB.db`

In [5]:
%%sql
SELECT name FROM sqlite_master WHERE type='table';

Running query in 'sqlite:///FinalDB.db'

+------------------------+
|          name          |
+------------------------+
|      CENSUS_DATA       |
| CHICAGO_PUBLIC_SCHOOLS |
|   CHICAGO_CRIME_DATA   |
+------------------------+

You can now proceed to the the following questions. Please note that a graded assignment will follow this lab and there will be a question on each of the problems stated below. It can be from the answer you received or the code you write for this problem. Therefore, please keep a note of both your codes as well as the response you generate.

## Problems

Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table.

In [6]:
%%sql
SELECT count(CASE_NUMBER) as [Total number of crimes]
FROM CHICAGO_CRIME_DATA

Running query in 'sqlite:///FinalDB.db'

+------------------------+
| Total number of crimes |
+------------------------+
|          533           |
+------------------------+

### Problem 2

##### List community area names and numbers with per capita income less than 11000.

In [7]:
%%sql
--2.When you list all case numbers for crimes involving a minor قاصر , how many rows of data are retrieved?
SELECT  COMMUNITY_AREA_NUMBER AS [Community Area Number],COMMUNITY_AREA_NAME AS [Community Area Name],
PER_CAPITA_INCOME AS [Per Capita Income]
FROM CENSUS_DATA
WHERE PER_CAPITA_INCOME < 11000
GROUP BY PER_CAPITA_INCOME;

Running query in 'sqlite:///FinalDB.db'

+-----------------------+---------------------+-------------------+
| Community Area Number | Community Area Name | Per Capita Income |
+-----------------------+---------------------+-------------------+
|          54.0         |      Riverdale      |        8201       |
|          30.0         |    South Lawndale   |       10402       |
|          37.0         |     Fuller Park     |       10432       |
|          26.0         |  West Garfield Park |       10934       |
+-----------------------+---------------------+-------------------+

### Problem 3

##### List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)

In [8]:
%%sql
SELECT CASE_NUMBER AS [Case Number]
FROM CHICAGO_CRIME_DATA
WHERE description LIKE '%minor%';

Running query in 'sqlite:///FinalDB.db'

+-------------+
| Case Number |
+-------------+
|   HL266884  |
|   HK238408  |
+-------------+

### Problem 4

##### List all kidnapping crimes involving a child?

In [9]:
%%sql
SELECT *
FROM CHICAGO_CRIME_DATA
WHERE description LIKE '%child%'
AND PRIMARY_TYPE LIKE '%KIDNAPPING%';

Running query in 'sqlite:///FinalDB.db'

+---------+-------------+------------+----------------------+------+--------------+--------------------------+----------------------+--------+----------+------+----------+------+-----------------------+---------+--------------+--------------+------+-------------+--------------+-------------------------------+
|    ID   | CASE_NUMBER |    DATE    |        BLOCK         | IUCR | PRIMARY_TYPE |       DESCRIPTION        | LOCATION_DESCRIPTION | ARREST | DOMESTIC | BEAT | DISTRICT | WARD | COMMUNITY_AREA_NUMBER | FBICODE | X_COORDINATE | Y_COORDINATE | YEAR |   LATITUDE  |  LONGITUDE   |            LOCATION           |
+---------+-------------+------------+----------------------+------+--------------+--------------------------+----------------------+--------+----------+------+----------+------+-----------------------+---------+--------------+--------------+------+-------------+--------------+-------------------------------+
| 5276766 |   HN144152  | 2007-01-26 | 050XX W VAN BUREN ST | 1792 |  KIDNAPPING  | CHILD ABDUCTION/STRANGER |        STREET        |   0    |    0     | 1533 |    15    | 29.0 |          25.0         |    20   |  1143050.0   |  1897546.0   | 2007 | 41.87490841 | -87.75024931 | (41.874908413, -87.750249307) |
+---------+-------------+------------+----------------------+------+--------------+--------------------------+----------------------+--------+----------+------+----------+------+-----------------------+---------+--------------+--------------+------+-------------+--------------+-------------------------------+

### Problem 5

##### List the kind of crimes that were recorded at schools. (No repetitions)

In [10]:
%%sql
SELECT DISTINCT PRIMARY_TYPE AS [Kind Of Crimes]
FROM CHICAGO_CRIME_DATA
WHERE LOCATION_DESCRIPTION LIKE '%school%'

Running query in 'sqlite:///FinalDB.db'

+------------------------+
|     Kind Of Crimes     |
+------------------------+
|        BATTERY         |
|    CRIMINAL DAMAGE     |
|       NARCOTICS        |
|        ASSAULT         |
|   CRIMINAL TRESPASS    |
| PUBLIC PEACE VIOLATION |
+------------------------+

### Problem 6

##### List the type of schools along with the average safety score for each type.

In [11]:
%%sql
SELECT [Elementary, Middle, or High School] AS [School Type],
AVG(SAFETY_SCORE) AS [Average Safety Score]
FROM CHICAGO_PUBLIC_SCHOOLS
GROUP BY [Elementary, Middle, or High School]

Running query in 'sqlite:///FinalDB.db'

+-------------+----------------------+
| School Type | Average Safety Score |
+-------------+----------------------+
|      ES     |  49.52038369304557   |
|      HS     |  49.62352941176471   |
|      MS     |         48.0         |
+-------------+----------------------+

### Problem 7

##### List 5 community areas with highest % of households below poverty line

In [12]:
%%sql
SELECT COMMUNITY_AREA_NUMBER AS [Community Area Number],COMMUNITY_AREA_NAME AS [Community Area Name],
PERCENT_HOUSEHOLDS_BELOW_POVERTY AS [Percent Of Households]
FROM CENSUS_DATA
ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC
LIMIT 5;

Running query in 'sqlite:///FinalDB.db'

+-----------------------+---------------------+-----------------------+
| Community Area Number | Community Area Name | Percent Of Households |
+-----------------------+---------------------+-----------------------+
|          54.0         |      Riverdale      |          56.5         |
|          37.0         |     Fuller Park     |          51.2         |
|          68.0         |      Englewood      |          46.6         |
|          29.0         |    North Lawndale   |          43.1         |
|          27.0         |  East Garfield Park |          42.4         |
+-----------------------+---------------------+-----------------------+

### Problem 8

##### Which community area is most crime prone? Display the coumminty area number only.

In [13]:

%%sql
SELECT COMMUNITY_AREA_NUMBER AS [Community Area Number]
FROM CHICAGO_CRIME_DATA
GROUP BY COMMUNITY_AREA_NUMBER
ORDER BY COUNT(*) DESC
LIMIT 1;

Running query in 'sqlite:///FinalDB.db'

+-----------------------+
| Community Area Number |
+-----------------------+
|          25.0         |
+-----------------------+


Double-click **here** for a hint

<!--
Query for the 'community area number' that has most number of incidents
-->

### Problem 9

##### Use a sub-query to find the name of the community area with highest hardship index

In [14]:
%%sql
SELECT COMMUNITY_AREA_NAME AS [Community Area Name]
FROM CENSUS_DATA
WHERE HARDSHIP_INDEX = (SELECT MAX(HARDSHIP_INDEX) FROM CENSUS_DATA);

Running query in 'sqlite:///FinalDB.db'

+---------------------+
| Community Area Name |
+---------------------+
|      Riverdale      |
+---------------------+

### Problem 10

##### Use a sub-query to determine the Community Area Name with most number of crimes?

In [15]:
%%sql
SELECT COMMUNITY_AREA_NAME AS [Community Area Name]
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER = (SELECT COMMUNITY_AREA_NUMBER AS [Community Area Number]
FROM CHICAGO_CRIME_DATA
GROUP BY COMMUNITY_AREA_NUMBER
ORDER BY COUNT(*) DESC
LIMIT 1);

Running query in 'sqlite:///FinalDB.db'

+---------------------+
| Community Area Name |
+---------------------+
|        Austin       |
+---------------------+